require:
  - rubocop-rails
  - rubocop-minitest
AllCops:
    NewCops: enable
    Exclude:
      - 'node_modules/**/*'
      - 'tmp/**/*'
      - 'vendor/**/*'
      - '.git/**/*'
      - 'db/**/*'
      - 'config/**/*'
      - 'script/**/*'
      - 'bin/**/*'
      - !ruby/regexp /z_unused_code\.rb$/
Layout/EndOfLine:
  Enabled: false
Layout/LineLength:
  Max: 120
  AllowedPatterns: ['(\A|\s)#']
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/OptionalBooleanParameter:
  AllowedMethods: ['position']
Style/RegexpLiteral:
  EnforcedStyle: slashes
Naming/PredicateName:
  AllowedMethods: ['is_logged_in?']
Style/SymbolArray:
  EnforcedStyle: brackets
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Rails/RefuteMethods:
  EnforcedStyle: refute
Rails/SkipsModelValidations:
  AllowedMethods: ["increment!"]
Style/LineEndConcatenation:
  Enabled: false
Minitest/MultipleAssertions:
  Max: 6
Style/StringConcatenation:
  Exclude:
    - 'app/models/whatsapp.rb'
