default: &default

 attendance_statuses:
  - booked
  - attended
  - cancelled early
  - cancelled late
  - no show
 
#  product_colors:
#   - none
#   - coach
#   - senior coach
#   - head coach
#   - elite

 product_colors:
  - none
  - coach tier1
  - coach tier2
  - coach tier3
  - senior coach
  - head coach
  - founder

 discount_applications:
  - as applicable
  - student 
  - friends_and_family
  - first_package
  - renewal_pre_package_expiry
  - renewal_post_package_expiry
  - renewal_pre_trial_expiry
  - renewal_post_trial_expiry

 discount_rationales:
  - Base
  - Commercial
  - Discretion
  - Oneoff
  - Status
  - Renewal

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

#  gst_rate:
#   - 18
