default: &default

 attendance_statuses:
  - booked
  - attended
  - cancelled early
  - cancelled late
  - no show

 discount_names:
  - None 
  - Buddy
  - Complimentary
  - Friends & Family
  - New Year 2024
  - Student
  - First Package
  - Renewal of Package Before Expiry
  - Renewal of Package After Expiry
  - Renewal of Trial Before Expiry
  - Renewal of Trial After Expiry

 discount_applications:
  - as applicable
  - student 
  - friends_and_family
  - first_package
  - renewal_pre_package_expiry
  - renewal_post_package_expiry
  - renewal_pre_trial_expiry
  - renewal_post_trial_expiry

 discount_rationales:
  - Base
  - Discretion
  - Oneoff
  - Status
  - Renewal

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default

  #  payment_methods:
#   - A&R conversion
#   - Card-Credit
#   - Card-Debit
#   - Cash
#   - Cheque
#   - ClassPass
#   - Fitternity
#   - Google Pay
#   - Instamojo
#   - NEFT
#   - Not applicable
#   - Not paid
#   - Paid to instructor
#   - PayTM
#   - Razorpay

#  gst_rate:
#   - 18

#  settings:
#    amendment_count: 3
#    visibility_window_hours_before: 2
#    visibility_window_days_ahead: 6
#    booking_window_days_before: 2
#    booking_window_minutes_before: -5
