default: &default

 timetable_id: 6
 window_capacity: 8

 attendance_statuses:
  - booked
  - attended
  - cancelled early
  - cancelled late
  - no show
 
 workout_group_services:
  - group
  - online
  - pt

 discount_applications:
  - as applicable
  - student 
  - friends_and_family
  - first_package
  - renewal_pre_package_expiry
  - renewal_post_package_expiry
  - renewal_pre_trial_expiry
  - renewal_post_trial_expiry

 discount_rationales:
  - Base
  - Commercial
  - Discretion
  - Oneoff
  - Status
  - Renewal

development:
  <<: *default
  timetable_id: 1

test:
  <<: *default
  timetable_id: 4  

production:
  <<: *default

#  gst_rate:
#   - 18
