default: &default

#  display_timetable_id: 10
#  wkclass_make_timetable_id: 10
 window_capacity: 8
 recipient_pagination: 200
 wkclassmaker_advance: 4
 package_expiry_message_days: 3
 trial_expiry_message_days: 2

 booking_statuses:
  - booked
  - attended
  - cancelled early
  - cancelled late
  - no show
 
 workout_group_services:
  - group
  - online
  - pt

 discount_applications:
  - as applicable
  - student 
  - friends_and_family
  - first_package
  - renewal_pre_package_expiry
  - renewal_post_package_expiry
  - renewal_pre_trial_expiry
  - renewal_post_trial_expiry

 discount_rationales:
  - Base
  - Commercial
  - Discretion
  - Oneoff
  - Status
  - Renewal

 genders:
  - female
  - male
  - other
  - prefer not to say

development:
  <<: *default
  display_timetable_id: 1
  wkclass_make_timetable_id: 1

test:
  <<: *default
  display_timetable_id: 4
  wkclass_make_timetable_id: 4  

production:
  <<: *default
